# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: "spellchecking.CorrectSpelling"

   #- name: "spellchecking1.SpellCheckerCorrection"
     #language: "de"
     #distance: 2
     #word_freq_file: "resources/usa.txt


   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 2
     max_ngram: 4
   - name: DIETClassifier
     epochs: 200
   # other components
   - name: FallbackClassifier
     threshold: 0.8


policies:
   - name: RulePolicy
     core_fallback_threshold: 0.95
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
   - name: AugmentedMemoizationPolicy 
     max_history: 10
   - name: TEDPolicy
     max_history: 5
     epochs: 200
     batch_size:
     - 32
     - 64